name: CI

on:
  pull_request:
    branches:
    - v2

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
        uses: actions/checkout@v2
          with:
            fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep packages/ | xargs)"
  preview-publish:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - uses: actions/github-script@v5
    - name: install dependencies
      run: cd $GITHUB_WORKSPACE && npm i
    - name: publish preview version
      run: echo 'Not ready yet'
      # run: cd $GITHUB_WORKSPACE && npx tsx scripts/run_publish.ts ${{needs.changedfiles.outputs.ts}}
